### ISSUE TITLE
Install instructions with optional packages

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/olinda#10]
Olinda should be modular so that users only install what they need. In the current case, Ersilia and ZairaChem are only required when actually running a ZairaChem model distillation.  This can be specified in the PyProject.toml file easily as different options, you can have a look at Ersilia's repository for inspiration, where the different options are set out as extras.

For example, this means that I can install olinda inside ZairaChem without actually installing ZairaChem (which will be installed at the end of the pipeline) preventing errors from these double importing packages.

Also, this means that when olinda "base" is installed, simply calling the command Olinda the pipeline should not crash as we are not requiring ZairaChem at the moment.

**Comment by JHlozek** [comment]
Olinda now by default does not install ersilia and zairachem unless the install specifies 'olinda[ersilia]' or 'olinda[zairachem]'.

I can 'import olinda' in a standalone environment and the installation also works from ZairaChem.

However, there's a problem installing Olinda[ersilia] due to the pandas version mismatch between v1 and v2, also mentioned here:  https://github.com/ersilia-os/zaira-chem/issues/45#issue

**Comment by GemmaTuron** [comment]
Thanks @JHlozek 
To keep all issues in one place I will close this one as completed and then figure out the packaging issues when we first solve the ersilia version usage - reporting on the issue you are linking in ZairaChem
